### PR TITLE
Adding detekt static analyzer

### PR DESCRIPTION
**Pull request by akuleshov7**
### What's done:
- fixed basic issues found by detekt;
- updated corresponding task in actions;

### What's in focus:
- Catching and throwing too general exceptions. Logic should be revised;
- Performance issues with SpreadOperator are suppressed;

### CODE REVIEW

File: reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/generation/code/generator/Util.kt [hunk 1]
```diff
@@ -17,8 +17,6 @@ private fun FunSpec.Builder.generateBody(
     return build()
 }
 
-fun statement(format: String, args: List<Any>): CodeBlock = statement(format, *args.toTypedArray())
```
Comment (akuleshov7) [inline reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/generation/code/generator/Util.kt:20]: I moved this method to the place with it's only usage. It should be better for a performance.

File: reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt [hunk 2]
```diff
@@ -50,6 +46,7 @@ class ImportChecker {
                 } catch (e: Throwable) {
```
Comment (akuleshov7) [inline reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt:46]: What kind of exceptions you tried to catch here? This is not a good practice to catch Throwable

File: reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt [hunk 3]
```diff
@@ -31,17 +31,13 @@ class ImportChecker {
...
             .filter { Modifier.isPublic(it.modifiers) }
             .filter {
-                try {
-                    // Skip if no canonical name
-                    it.canonicalName != null
-                } catch (e: Throwable) {
-                    // Skip if canonical name cannot be resolved
-                    false
-                }
+                if (it == null) false else it.canonicalName != null
```
Comment (akuleshov7) [inline reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt:40]: Please double check it. I haven't found any possible thrown exceptions except an NPE here

File: reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt [hunk 4]
```diff
@@ -31,17 +31,13 @@ class ImportChecker {
         )
 
         // Get all classes (each class is subtype of java.lang.Object)
+        // FIXME: logic should be revised here, as caught exception is too generic (what kind of exception was intended to catch?)
+        @Suppress("SwallowedException", "TooGenericExceptionCaught")
```
Comment (akuleshov7) [inline reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt:35]: "SwallowedException" and "TooGenericExceptionCaught" - Are last problems left and suppressed right now. But I cannot understand what kind of PitFall have you seen here.

**Comment by nbirillo** [comment]
@akuleshov7 thank you a lot! I will check it tomorrow, sorry for the delay, December is a very hard month

File: reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt (hunk 2 above)
Comment (nbirillo) [reply reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt:47]: We use Reflection at the compile-time with the `compileClasspath` configuration imports and we can catch some unexpected errors like `SecurityException` or `NoClassDefFoundError` since some classes can not be loaded at the compile time for an unexpected reason. 
This can happen if, for example, the included libraries use other libraries that may not be available at compile time.
I know that it is bad practice to catch too general errors, but I am not sure that we can predict the java reflections behaviour here. 
Specifically, in this case, it seems to me that we can leave this method of error handling.  At least until we find a really good way to test this behaviour, for example, fuzzing would be nice here I think.

In any case, filtering is only used in the Smart Reflect part and does not affect the main functionality of the plugin. What do you think?

File: reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt (hunk 3 above)
Comment (nbirillo) [reply reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt:41]: I answered below, this case is the same

Comment (akuleshov7) [reply reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt:41]: got it, I will revert it

File: reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt (hunk 2 above)
Comment (akuleshov7) [reply reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt:47]: Yes, it makes sense, I totally forgot about things like `NoClassDefFoundError`. Let's suppress it then

Comment (nbirillo) [reply reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt:47]: maybe we should add a comment in the code to clarify why we are using such a common error here

File: reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt (hunk 3 above)
Comment (nbirillo) [reply reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt:41]: thank you a lot!

**Comment by akuleshov7** [comment]
@nbirillo finally fixed review notes, thanks. Sorry, that it took so long, damn December Let's move on 🚀

File: reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt (hunk 3 above)
Comment (akuleshov7) [reply reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt]: fixed

File: reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt (hunk 2 above)
Comment (akuleshov7) [reply reflekt-plugin/src/main/kotlin/org/jetbrains/reflekt/plugin/scripting/ImportChecker.kt:54]: done

**Review by nbirillo — APPROVED** [review]
Great! Thank you a lot! 🙌

Yeah, December is a very hard month...
